--DROP TABLE SALESFORCE_FIXTURES;
CREATE TABLE SALESFORCE_FIXTURES (
  ID            SERIAL        PRIMARY KEY,
  USERNAME      VARCHAR(255)   NOT NULL,
  NAME          VARCHAR(255)   NOT NULL,
  YAML          TEXT           NOT NULL,
  INSERT_DATE   TIMESTAMP     NOT NULL,
  UPDATE_DATE   TIMESTAMP     NOT NULL
)
;

